language: python

sudo: required

python:
  - "2.7"

before_install:
  - cd edge/

install:
  - pip install -r requirements.txt
  - pip install coveralls --use-mirrors

script: 
  - coverage run --source=./ manage.py test
  
after_success:
  - coveralls
