# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry', models.CharField(max_length=255, verbose_name='registry')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('period', models.CharField(max_length=255, verbose_name='period')),
            ],
        ),
    ]
