# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171004_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('menu', models.CharField(max_length=255, verbose_name='menu')),
                ('code', models.IntegerField(verbose_name='code')),
                ('work_load', models.IntegerField(verbose_name='work_load')),
            ],
        ),
    ]
